--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12 (Debian 15.12-1.pgdg120+1)
-- Dumped by pg_dump version 15.12 (Debian 15.12-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Appointments" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "AppointmentDate" timestamp with time zone NOT NULL,
    "SymptomsDescription" text,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Appointments" OWNER TO postgres;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "PasswordHash" text,
    "Role" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AccessFailedCount" integer DEFAULT 0 NOT NULL,
    "ConcurrencyStamp" text,
    "Email" character varying(256),
    "EmailConfirmed" boolean DEFAULT false NOT NULL,
    "LockoutEnabled" boolean DEFAULT false NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "NormalizedEmail" character varying(256),
    "NormalizedUserName" character varying(256),
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean DEFAULT false NOT NULL,
    "SecurityStamp" text,
    "TwoFactorEnabled" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- Name: Departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Departments" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public."Departments" OWNER TO postgres;

--
-- Name: Doctors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Doctors" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "DepartmentId" uuid NOT NULL,
    "SpecializationId" uuid NOT NULL,
    "LicenseNumber" character varying(50) NOT NULL,
    "YearsOfExperience" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Doctors" OWNER TO postgres;

--
-- Name: HospitalRooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."HospitalRooms" (
    "Id" uuid NOT NULL,
    "RoomNumber" integer NOT NULL,
    "Capacity" integer NOT NULL,
    "CurrentPatients" integer NOT NULL
);


ALTER TABLE public."HospitalRooms" OWNER TO postgres;

--
-- Name: MedicalRecords; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MedicalRecords" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "Diagnosis" text NOT NULL,
    "Treatment" text,
    "VisitDate" timestamp with time zone NOT NULL
);


ALTER TABLE public."MedicalRecords" OWNER TO postgres;

--
-- Name: Nurses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Nurses" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "DepartmentId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Nurses" OWNER TO postgres;

--
-- Name: PatientRoomAssignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatientRoomAssignments" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "RoomId" uuid NOT NULL,
    "AssignedDate" timestamp with time zone NOT NULL,
    "ReleasedDate" timestamp with time zone
);


ALTER TABLE public."PatientRoomAssignments" OWNER TO postgres;

--
-- Name: Patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Patients" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Gender" character varying(10) NOT NULL,
    "PhoneNumber" character varying(20),
    "Address" character varying(255),
    "EmergencyContact" character varying(255),
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Patients" OWNER TO postgres;

--
-- Name: Prescriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Prescriptions" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "MedicineName" character varying(255) NOT NULL,
    "Dosage" character varying(100) NOT NULL,
    "Instructions" text,
    "PrescribedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Prescriptions" OWNER TO postgres;

--
-- Name: Specializations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Specializations" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public."Specializations" OWNER TO postgres;

--
-- Name: WorkSchedules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WorkSchedules" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "WorkDate" timestamp with time zone NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."WorkSchedules" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Appointments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Appointments" ("Id", "PatientId", "DoctorId", "AppointmentDate", "SymptomsDescription", "Status", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUsers" ("Id", "UserName", "FirstName", "LastName", "PasswordHash", "Role", "CreatedAt", "AccessFailedCount", "ConcurrencyStamp", "Email", "EmailConfirmed", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled") FROM stdin;
d73b62ef-001e-4cc1-94b8-40e642eeffd5	admin@admin.com	admin	admin	AQAAAAIAAYagAAAAEJtjFg5+7QIH4jqW1GF5qMXw0wN0iMkvuHuaipJI7CylBhGptnRYFjIMyuvsOjpBNw==	admin	2025-04-07 21:26:05.342132+00	0	2eda0168-bd09-4bfa-91ad-49e9d33a7e93	admin@admin.com	f	t	\N	ADMIN@ADMIN.COM	ADMIN@ADMIN.COM	\N	f	7KEL2C2R67U2NKFA43WV7AM34JGVEH72	f
63ee9424-f62b-499b-b3c7-2236c1478624	davidjosipovic19@gmail.com	David	Josipovic	AQAAAAIAAYagAAAAEN8XmwcvFRM++nXHOApOU/PuPljO5zxAqgRAOYHMiHPbDxjc7H/5SaqhPt7n8Qy7eg==	doctor	2025-04-14 16:02:57.671192+00	0	d597390e-39a1-4b63-9be4-02ca49a0c022	davidjosipovic19@gmail.com	f	t	\N	DAVIDJOSIPOVIC19@GMAIL.COM	DAVIDJOSIPOVIC19@GMAIL.COM	\N	f	3ERPHX67KD7GGYXMDTVWODCKAUVKEJBP	f
\.


--
-- Data for Name: Departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Departments" ("Id", "Name") FROM stdin;
b6572083-ba06-4a28-ba72-81cecd7021f3	kretenizam
0cce82f4-f227-4d8a-8071-0470adeb0d83	2332
4d6a5134-4a73-4eac-b691-0ab904af36b3	ioioioio
\.


--
-- Data for Name: Doctors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Doctors" ("Id", "UserId", "DepartmentId", "SpecializationId", "LicenseNumber", "YearsOfExperience", "CreatedAt") FROM stdin;
4007a2a7-406b-4835-8f90-0058d005ad91	63ee9424-f62b-499b-b3c7-2236c1478624	b6572083-ba06-4a28-ba72-81cecd7021f3	6c17aa35-80b1-4a37-b3ac-5dc32249238f	LIC-835819	8	2025-04-14 16:28:07.043289+00
09fbd5f3-389e-4b6d-82e7-0228de26e4eb	63ee9424-f62b-499b-b3c7-2236c1478624	b6572083-ba06-4a28-ba72-81cecd7021f3	6675461d-499d-4552-b4b6-56d0f6624985	LIC-670544	767	2025-04-15 07:09:50.356423+00
\.


--
-- Data for Name: HospitalRooms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."HospitalRooms" ("Id", "RoomNumber", "Capacity", "CurrentPatients") FROM stdin;
64e2474b-301c-48bd-9e4f-fdf05f440bee	67	8	0
\.


--
-- Data for Name: MedicalRecords; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MedicalRecords" ("Id", "PatientId", "DoctorId", "Diagnosis", "Treatment", "VisitDate") FROM stdin;
\.


--
-- Data for Name: Nurses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Nurses" ("Id", "UserId", "DepartmentId", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: PatientRoomAssignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PatientRoomAssignments" ("Id", "PatientId", "RoomId", "AssignedDate", "ReleasedDate") FROM stdin;
\.


--
-- Data for Name: Patients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Patients" ("Id", "FirstName", "LastName", "DateOfBirth", "Gender", "PhoneNumber", "Address", "EmergencyContact", "CreatedAt") FROM stdin;
8583f9e6-a828-4406-ba92-9a3c16a790d3	zadro	kadro	1990-12-21 00:00:00+00	Other	223232	aaa	3232323	2025-04-15 06:42:17.178425+00
\.


--
-- Data for Name: Prescriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Prescriptions" ("Id", "PatientId", "DoctorId", "MedicineName", "Dosage", "Instructions", "PrescribedAt") FROM stdin;
\.


--
-- Data for Name: Specializations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Specializations" ("Id", "Name") FROM stdin;
6c17aa35-80b1-4a37-b3ac-5dc32249238f	majmun
6675461d-499d-4552-b4b6-56d0f6624985	323
\.


--
-- Data for Name: WorkSchedules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."WorkSchedules" ("Id", "UserId", "WorkDate", "StartTime", "EndTime", "Status", "CreatedAt") FROM stdin;
98907ff3-deed-45a0-aa8d-67c19e956942	d73b62ef-001e-4cc1-94b8-40e642eeffd5	2025-04-02 00:00:00+00	07:00:00	14:00:00	working	2025-04-07 21:26:42.424643+00
4881f80e-fbaf-4c15-a32f-273624660c29	63ee9424-f62b-499b-b3c7-2236c1478624	2025-04-09 00:00:00+00	08:00:00	15:00:00	working	2025-04-14 16:15:16.576372+00
b3915113-3650-47cc-8d9d-f124220a247e	63ee9424-f62b-499b-b3c7-2236c1478624	2025-04-12 00:00:00+00	01:00:00	15:00:00	working	2025-04-14 16:15:22.086877+00
1748e912-761e-4f82-853b-fb23103d6268	63ee9424-f62b-499b-b3c7-2236c1478624	2025-04-17 00:00:00+00	13:00:00	15:00:00	working	2025-04-14 16:15:32.079981+00
1f516e4e-2565-47bc-8bbf-fc04b47df592	63ee9424-f62b-499b-b3c7-2236c1478624	2025-04-26 00:00:00+00	14:00:00	16:00:00	working	2025-04-14 16:15:41.607446+00
21ae16d9-349a-4b2e-858c-159775494894	63ee9424-f62b-499b-b3c7-2236c1478624	2025-04-03 00:00:00+00	07:00:00	15:00:00	working	2025-04-14 16:15:46.761946+00
f627b25c-46f5-43c7-8981-5f13258d2e13	63ee9424-f62b-499b-b3c7-2236c1478624	2025-04-22 00:00:00+00	07:00:00	14:00:00	working	2025-04-15 07:10:14.018706+00
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250223192711_InitialCreate	9.0.2
20250223194635_AddIdentitySupport	9.0.2
20250223195126_FixUserForeignKey	9.0.2
20250223200911_EnforceRoleConstraint	9.0.2
20250407212332_InitialMigration	9.0.2
\.


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Appointments PK_Appointments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id");


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Departments PK_Departments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Departments"
    ADD CONSTRAINT "PK_Departments" PRIMARY KEY ("Id");


--
-- Name: Doctors PK_Doctors; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doctors"
    ADD CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id");


--
-- Name: HospitalRooms PK_HospitalRooms; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HospitalRooms"
    ADD CONSTRAINT "PK_HospitalRooms" PRIMARY KEY ("Id");


--
-- Name: MedicalRecords PK_MedicalRecords; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedicalRecords"
    ADD CONSTRAINT "PK_MedicalRecords" PRIMARY KEY ("Id");


--
-- Name: Nurses PK_Nurses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Nurses"
    ADD CONSTRAINT "PK_Nurses" PRIMARY KEY ("Id");


--
-- Name: PatientRoomAssignments PK_PatientRoomAssignments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientRoomAssignments"
    ADD CONSTRAINT "PK_PatientRoomAssignments" PRIMARY KEY ("Id");


--
-- Name: Patients PK_Patients; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "PK_Patients" PRIMARY KEY ("Id");


--
-- Name: Prescriptions PK_Prescriptions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prescriptions"
    ADD CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("Id");


--
-- Name: Specializations PK_Specializations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Specializations"
    ADD CONSTRAINT "PK_Specializations" PRIMARY KEY ("Id");


--
-- Name: WorkSchedules PK_WorkSchedules; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WorkSchedules"
    ADD CONSTRAINT "PK_WorkSchedules" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_Appointments_DoctorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Appointments_DoctorId" ON public."Appointments" USING btree ("DoctorId");


--
-- Name: IX_Appointments_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Appointments_PatientId" ON public."Appointments" USING btree ("PatientId");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_Doctors_DepartmentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Doctors_DepartmentId" ON public."Doctors" USING btree ("DepartmentId");


--
-- Name: IX_Doctors_SpecializationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Doctors_SpecializationId" ON public."Doctors" USING btree ("SpecializationId");


--
-- Name: IX_Doctors_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Doctors_UserId" ON public."Doctors" USING btree ("UserId");


--
-- Name: IX_MedicalRecords_DoctorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MedicalRecords_DoctorId" ON public."MedicalRecords" USING btree ("DoctorId");


--
-- Name: IX_MedicalRecords_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MedicalRecords_PatientId" ON public."MedicalRecords" USING btree ("PatientId");


--
-- Name: IX_Nurses_DepartmentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Nurses_DepartmentId" ON public."Nurses" USING btree ("DepartmentId");


--
-- Name: IX_Nurses_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Nurses_UserId" ON public."Nurses" USING btree ("UserId");


--
-- Name: IX_PatientRoomAssignments_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PatientRoomAssignments_PatientId" ON public."PatientRoomAssignments" USING btree ("PatientId");


--
-- Name: IX_PatientRoomAssignments_RoomId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PatientRoomAssignments_RoomId" ON public."PatientRoomAssignments" USING btree ("RoomId");


--
-- Name: IX_Prescriptions_DoctorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Prescriptions_DoctorId" ON public."Prescriptions" USING btree ("DoctorId");


--
-- Name: IX_Prescriptions_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Prescriptions_PatientId" ON public."Prescriptions" USING btree ("PatientId");


--
-- Name: IX_WorkSchedules_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_WorkSchedules_UserId" ON public."WorkSchedules" USING btree ("UserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: Appointments FK_Appointments_Doctors_DoctorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("Id") ON DELETE CASCADE;


--
-- Name: Appointments FK_Appointments_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Doctors FK_Doctors_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doctors"
    ADD CONSTRAINT "FK_Doctors_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Doctors FK_Doctors_Departments_DepartmentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doctors"
    ADD CONSTRAINT "FK_Doctors_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES public."Departments"("Id") ON DELETE CASCADE;


--
-- Name: Doctors FK_Doctors_Specializations_SpecializationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doctors"
    ADD CONSTRAINT "FK_Doctors_Specializations_SpecializationId" FOREIGN KEY ("SpecializationId") REFERENCES public."Specializations"("Id") ON DELETE CASCADE;


--
-- Name: MedicalRecords FK_MedicalRecords_Doctors_DoctorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedicalRecords"
    ADD CONSTRAINT "FK_MedicalRecords_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("Id") ON DELETE CASCADE;


--
-- Name: MedicalRecords FK_MedicalRecords_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedicalRecords"
    ADD CONSTRAINT "FK_MedicalRecords_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- Name: Nurses FK_Nurses_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Nurses"
    ADD CONSTRAINT "FK_Nurses_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Nurses FK_Nurses_Departments_DepartmentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Nurses"
    ADD CONSTRAINT "FK_Nurses_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES public."Departments"("Id") ON DELETE CASCADE;


--
-- Name: PatientRoomAssignments FK_PatientRoomAssignments_HospitalRooms_RoomId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientRoomAssignments"
    ADD CONSTRAINT "FK_PatientRoomAssignments_HospitalRooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES public."HospitalRooms"("Id") ON DELETE CASCADE;


--
-- Name: PatientRoomAssignments FK_PatientRoomAssignments_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientRoomAssignments"
    ADD CONSTRAINT "FK_PatientRoomAssignments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- Name: Prescriptions FK_Prescriptions_Doctors_DoctorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prescriptions"
    ADD CONSTRAINT "FK_Prescriptions_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("Id") ON DELETE CASCADE;


--
-- Name: Prescriptions FK_Prescriptions_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prescriptions"
    ADD CONSTRAINT "FK_Prescriptions_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- Name: WorkSchedules FK_WorkSchedules_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WorkSchedules"
    ADD CONSTRAINT "FK_WorkSchedules_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

