services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj
    ports:
      - "5214:5214"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    restart: always
    command: dotnet watch run

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=docker
    restart: always
    command: npm run dev

  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile.migrations
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command: ["tail", "-f", "/dev/null"]

volumes:
  pgdata: {}
